//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proj2MvcFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emptable
    {
        public int empId { get; set; }
        public string empName { get; set; }
        public string empAddress { get; set; }
        public decimal empSalary { get; set; }
        public Nullable<int> DeptId { get; set; }
    
        public virtual DeptTable DeptTable { get; set; }
    }
}
